version: "2"

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gosec
    - govet
    - ineffassign
    - intrange
    - misspell
    - modernize
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - noctx
    - nolintlint
    - perfsprint
    - predeclared
    - reassign
    - recvcheck
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3
  nakedret:
    max-func-lines: 30
  nestif:
    min-complexity: 5
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unreachable-code
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  gosec: {}

formatters:
  enable:
    - gofmt

output:
  sort-order:
    - file
